### ISSUE TITLE
Add Exam Venues from PDF

### ISSUE THREAD

**Issue by ptayal76** [swciitg/smart-timetable#8]
### Summary
Write a function to make a CSV file from the midsem_venue.pdf (and similarly endsem_venue.pdf for endsem) file attached accordingly so as to find the venue(Room No.) of a given course code for a given roll_number. 
Add fields 'midsem_venue' and 'endsem_venue' in 'my_courses_nullable' in main.py and fetch their values by matching Roll number and course code from the CSV.
[midsem_venue.pdf](https://github.com/swciitg/smart-timetable/files/12775028/midsem_venue.pdf)

**Note: Create pull request in 'hacktober' branch**

**Comment by ugly-custard** [comment]
I want to try working on it!

**Comment by Hareesh-Nandigrama** [comment]
> I want to try working on it!

You have been assigned

**Comment by ugly-custard** [comment]
hey, could you check the pull request #13  I've made and let me know if there's things I should change.

**Comment by Hareesh-Nandigrama** [comment]
> hey, could you check the pull request #13 I've made and let me know if there's things I should change.

I've added a few comments in the PR

**Comment by ugly-custard** [comment]
could you check if there's anything else I should change?

**Comment by ugly-custard** [comment]
resolved them !
conflicts can be such a pain :pensive:

**Comment by Hareesh-Nandigrama** [comment]
😂 yaa
