### ISSUE TITLE
Add day wise Class Time

### ISSUE THREAD

**Issue by ptayal76** [swciitg/smart-timetable#9]
### Summary
Add 5 new columns (for each weekday) in courses_csv.csv and assign time according to slot time table attached.
Write the code for this in a new file.
In the JSON of my courses (main.py), add the day wise time fields (fetch them from csv).
the json for a particular course should look like this:
**(The time format must be as given: "08:00 - 08:55 AM")**
{
      "code": "CS 501",
      "course": "Parallel Algorithms",
      "slot": "D",
      "instructor": "Sajith Gopalan",
      "venue": "L1",
      "midsem": "2023-09-21T09:00:00.000Z",
      "endsem": "2023-11-22T09:00:00.000Z",
      "timings":{
		 "monday": "8:00-9:00 AM",
		 "tuesday": "10:00-11:00 AM",
		 "friday": "1:00-2:00 PM"
		}
    },

If a class isnt there on a particular day, nothing will be returned for that day in the week
[tt_slot.pdf](https://github.com/swciitg/smart-timetable/files/12775337/tt_slot.pdf)

**Note: Create pull request in 'hacktober' branch**

**Comment by dhaneshragu** [comment]
I would like to work on this

**Comment by Hareesh-Nandigrama** [comment]
@dhaneshragu you have assigned

**Comment by dhaneshragu** [comment]
> @dhaneshragu you have assigned

@Hareesh-Nandigrama, done. pls check
